//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myWebAPIService.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class cSalingManagementEntities : DbContext
    {
        public cSalingManagementEntities()
            : base("name=cSalingManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<M_UserAccount> M_UserAccount { get; set; }
        public DbSet<temp> temps { get; set; }
    
        public virtual int sp_MUserAccount_Delete()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MUserAccount_Delete");
        }
    
        public virtual ObjectResult<sp_MUserAccount_Get_Result> sp_MUserAccount_Get(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MUserAccount_Get_Result>("sp_MUserAccount_Get", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<sp_MUserAccount_GetAll_Result> sp_MUserAccount_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MUserAccount_GetAll_Result>("sp_MUserAccount_GetAll");
        }
    
        public virtual int sp_MUserAccount_Insert(string username, string password, Nullable<int> status)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MUserAccount_Insert", usernameParameter, passwordParameter, statusParameter);
        }
    
        public virtual int sp_MUserAccount_Update(string username, string password, Nullable<int> status)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("Password", password) :
                new ObjectParameter("Password", typeof(string));
    
            var statusParameter = status.HasValue ?
                new ObjectParameter("Status", status) :
                new ObjectParameter("Status", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_MUserAccount_Update", usernameParameter, passwordParameter, statusParameter);
        }
    }
}
