//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestMyWebService.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://schemas.datacontract.org/2004/07/MyService")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Age {
            get {
                return this.AgeField;
            }
            set {
                if ((object.ReferenceEquals(this.AgeField, value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRest")]
    public interface IRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRest/GetEmployees", ReplyAction="http://tempuri.org/IRest/GetEmployeesResponse")]
        TestMyWebService.ServiceReference1.Employee[] GetEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRest/GetEmployees", ReplyAction="http://tempuri.org/IRest/GetEmployeesResponse")]
        System.Threading.Tasks.Task<TestMyWebService.ServiceReference1.Employee[]> GetEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRest/GetEmployee", ReplyAction="http://tempuri.org/IRest/GetEmployeeResponse")]
        TestMyWebService.ServiceReference1.Employee GetEmployee(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRest/GetEmployee", ReplyAction="http://tempuri.org/IRest/GetEmployeeResponse")]
        System.Threading.Tasks.Task<TestMyWebService.ServiceReference1.Employee> GetEmployeeAsync(string Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRest/AddEmployee", ReplyAction="http://tempuri.org/IRest/AddEmployeeResponse")]
        void AddEmployee(TestMyWebService.ServiceReference1.Employee newEmp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRest/AddEmployee", ReplyAction="http://tempuri.org/IRest/AddEmployeeResponse")]
        System.Threading.Tasks.Task AddEmployeeAsync(TestMyWebService.ServiceReference1.Employee newEmp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestChannel : TestMyWebService.ServiceReference1.IRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestClient : System.ServiceModel.ClientBase<TestMyWebService.ServiceReference1.IRest>, TestMyWebService.ServiceReference1.IRest {
        
        public RestClient() {
        }
        
        public RestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestMyWebService.ServiceReference1.Employee[] GetEmployees() {
            return base.Channel.GetEmployees();
        }
        
        public System.Threading.Tasks.Task<TestMyWebService.ServiceReference1.Employee[]> GetEmployeesAsync() {
            return base.Channel.GetEmployeesAsync();
        }
        
        public TestMyWebService.ServiceReference1.Employee GetEmployee(string Id) {
            return base.Channel.GetEmployee(Id);
        }
        
        public System.Threading.Tasks.Task<TestMyWebService.ServiceReference1.Employee> GetEmployeeAsync(string Id) {
            return base.Channel.GetEmployeeAsync(Id);
        }
        
        public void AddEmployee(TestMyWebService.ServiceReference1.Employee newEmp) {
            base.Channel.AddEmployee(newEmp);
        }
        
        public System.Threading.Tasks.Task AddEmployeeAsync(TestMyWebService.ServiceReference1.Employee newEmp) {
            return base.Channel.AddEmployeeAsync(newEmp);
        }
    }
}
