//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Account
    {
        public string Username { get; set; }
        public string Password { get; set; }
        public string EmployeeID { get; set; }
        public string RoleID { get; set; }
        public Nullable<int> AccountStatus { get; set; }
    }
}
