//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Category
    {
        public string CategoryID { get; set; }
        public string CategoryName { get; set; }
        public string Cate_Description { get; set; }
        public string Cate_Image { get; set; }
        public Nullable<int> Cate_Status { get; set; }
    }
}
