//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_District
    {
        public string DistrictID { get; set; }
        public string District_Name { get; set; }
        public string City { get; set; }
        public Nullable<int> District_Status { get; set; }
    }
}
