//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Employee
    {
        public string EmployeeID { get; set; }
        public string DepartmentID { get; set; }
        public string EmployeeName { get; set; }
        public string Employee_IDCard { get; set; }
        public string Emp_Address { get; set; }
        public Nullable<System.DateTime> Emp_DateOfBirth { get; set; }
        public string Emp_Phone { get; set; }
        public string Emp_SubPhone { get; set; }
        public Nullable<double> Salary { get; set; }
        public Nullable<int> Employee_Status { get; set; }
    }
}
