//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_ProductInfo
    {
        public string ProductID { get; set; }
        public string ProductName { get; set; }
        public string Category { get; set; }
        public Nullable<int> Pro_InStock { get; set; }
        public string Pro_Image { get; set; }
        public Nullable<double> Pro_Price { get; set; }
        public string Pro_Desciptions { get; set; }
        public string Pro_Preservation { get; set; }
        public string Pro_HowToUse { get; set; }
        public string Pro_Origin { get; set; }
        public Nullable<int> Pro_Status { get; set; }
    }
}
