//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Supplier
    {
        public string SupplierID { get; set; }
        public string SupplierName { get; set; }
        public string Supp_Address { get; set; }
        public string Supp_Phone { get; set; }
        public string Supp_Sub_Phone { get; set; }
        public string Supp_Email { get; set; }
        public string Supp_Website { get; set; }
        public string Supp_Image { get; set; }
        public Nullable<int> Supplier_Status { get; set; }
    }
}
