//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_Ward
    {
        public string WardID { get; set; }
        public string Ward_Name { get; set; }
        public string District { get; set; }
        public Nullable<int> Ward_Status { get; set; }
    }
}
