//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_OrderDetail
    {
        public string OD_OrderID { get; set; }
        public string OD_ProductID { get; set; }
        public System.DateTime OD_ImportDate { get; set; }
        public Nullable<int> OD_Quantity { get; set; }
        public Nullable<double> OD_SellingPrice { get; set; }
        public Nullable<double> OD_TotalAmount { get; set; }
        public Nullable<int> OD_Status { get; set; }
    }
}
