//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order
    {
        public string OrderID { get; set; }
        public string Order_CustomerID { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedUser { get; set; }
        public string Order_Memo { get; set; }
        public Nullable<System.DateTime> Order_ShipTime { get; set; }
        public Nullable<int> Order_Status { get; set; }
    }
}
